---
# tasks file for vpp
- name: Install vpp repo
  copy: src=files/fdio.repo dest=/etc/yum.repos.d/fdio.repo mode=0600 force=no
  tags: nginx
- rpm_key:
    state: present
    key: "https://packagecloud.io/fdio/1810/gpgkey"

- name: update repo cache for the new repo
  command: yum -q makecache -y --disablerepo=* --enablerepo=fdio_1810

- name: Install packages
  package: name={{item}} state=installed
  with_items:
  - pygpgme
  - yum-utils
  - vpp
  - vpp-plugins
  - vpp-api-python
  - vpp-api-lua
  - vpp-api-java
  - honeycomb
  tags: packages

- name: Copy DPDK tools
  copy:
    src: files/tools/{{ item}}
    dest: /usr/sbin
    mode: 0755
  with_items:
    ['cpu_layout.py','dpdk-devbind.py','dpdk-pmdinfo.py','dpdk-setup.sh','dpdk-telemetry-client.py']
  tags: tools




